### ISSUE TITLE
Allow pro-brno users

### ISSUE THREAD

**Issue by sinus-x** [fit-ctu-discord/honza-botner-old#10]
ČVUT users are welcome on VUT discord, if they behave. You, on the other hand, have built a wall. We hope there is a compromise; there's no need for `anti-brno` features. Give us a chance!

Make us a verify test, make naughty list to keep track of s__tposters. People have to stick together in these difficult times. Let's not throw stones at each other, we are adults, after all.

**Comment by jirkavrba** [comment]
This is actually a valid point, we have thought about this and there is a role with the same permissions that can be manually assigned if needed, you are welcome to join the server and message one of the channels, that are visible without the permissions of an authenticated user.

https://discordapp.com/invite/BWGrq9E
