### ISSUE TITLE
Architektura

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner-old#20]
Zvolit vhodnou architekturu pro snadnou údržbu a rozšíření. Zřejmě vertikálně členěná (moduly/featury), možná současně i horizontálně (vrstvy). Něco jako Clean Architecture?

- [ ] prozkoumat a zvolit architekturu
- [ ] vymyslet jak se budou moduly pojit

Začátek po státnicích. 👍

**Comment by jirkavrba** [comment]
Rozhodně bych to postavil na Spring Boot, je tam lepší DI, potenciál pro Web Dashboard?

**Comment by jirkavrba** [comment]
https://gitlab.com/jirkavrba/chef Mám tam implementované i ACL a Permissions policy pro commandy
